### PR TITLE
Map Markers UI Update

### LINKED ISSUE #219: Match Map Screen UI to Figma Screen
-⁠ Improve the appearance of the Providers et Service Requests markers on their respective maps: they should match the UI designed on Figma.

Image

### PR DESCRIPTION
**Pull request by manunam2002**
### Description:
This PR replaces the basic map markers with custom composable markers, in the style of the figma screen.

### Related Issues:
- Fixes #219 

### Changes Made:
- Created `MapMarker` composable to replace standard markers
- Implemented the logic to load markers images before the map is loaded, as `GoogleMap` items do not support recomposition

### Testing
Sadly most `GoogleMap` content is not testable, so while some tests where added where it was possible, other where simply not possible to implements.

### CODE REVIEW

**Review by yshdb5 — APPROVED** [review]
### Overall Comment
This PR introduces several improvements to the map-related components in the project, including enhancements to the `MapScreen`, `ProviderMapScreen`, `SeekerMapScreen`, and corresponding tests. The changes focus on improving the overall appearance of the markers, making them ressemble the Figma screens that we designed.

### Strong Elements
1. **Enhanced Markers**: 
 - The introduction of `MapMarker` composable significantly enhance the appearance,  usability and interactivity of map markers. It brings a richer user experience by displaying images along of other information for each marker and providing clickable markers.
- Refactoring `MapContent` and creating `MapMarker` as a separate composable improve the readability and maintainability of the code. The use of `LaunchedEffect` to handle asynchronous image loading and marker updates is well-implemented.
2. **Test Coverage**: The updated tests in `MarketDataTest` ensure that the new properties are properly validated. This is crucial for maintaining code quality and reliability.

### Areas for Improvement
1. **Clicking on providers' marker**: clicking on a provider marker should navigate to the `ProviderInfoScreen` of the corresponding user.
2. **Error Handling**: While the `imageBitmapFromUrl` function handles errors by providing a placeholder, it could be beneficial to log these errors or handle them more gracefully to aid in debugging.

### Conclusion
Overall, this PR significantly enhances the map functionalities and user experience within the application. The additions are well-implemented and tested, contributing positively to the project's maintainability and usability. Addressing the very minor area for improvement will give a perfect code. Great work!

**Review by ethanboren — COMMENTED** [review]
### Description:
- Added ImageBitmap to MarkerData in MapScreenTest.kt for better marker representation.
- Introduced CountDownLatch to ensure the map is fully loaded before assertions.
- Enhanced ProviderMapScreen and SeekerMapScreen to include images in markers.
- Used LaunchedEffect to dynamically update markers based on data changes.


### Good things
- The tests you did really help our project still work even in the future. It also makes it possible to maintain high line coverage. Thanks for that

### Things to Modify
1. ProviderMap.kt:
   - The onClick functionality for markers is currently a TODO. Implement this or provide a comment explaining the expected behavior and future implementation plan.

2. SeekerMap.kt:
   - Ensure the `imageBitmapFromUrl `function handles all possible edge cases, such as null or invalid URLs.
  
3. In general
   - You can use external methods to avoid code duplication. Which makes the code clearer and more readable
   - You could add a few comments in the code at tricky moments to make rereading easier.
   - I also read the pull review that Yshai did and I follow him on certain points (so I won't repeat them)
 
### Overall
- Overall, you did a very good job. The PR was necessary for the smooth running of the project

**Comment by ethanboren** [comment]
> ### Description:
> * Added ImageBitmap to MarkerData in MapScreenTest.kt for better marker representation.
> * Introduced CountDownLatch to ensure the map is fully loaded before assertions.
> * Enhanced ProviderMapScreen and SeekerMapScreen to include images in markers.
> * Used LaunchedEffect to dynamically update markers based on data changes.
> 
> ### Good things
> * The tests you did really help our project still work even in the future. It also makes it possible to maintain high line coverage. Thanks for that
> 
> ### Things to Modify
> 1. ProviderMap.kt:
>    
>    * The onClick functionality for markers is currently a TODO. Implement this or provide a comment explaining the expected behavior and future implementation plan.
> 2. SeekerMap.kt:
>    
>    * Ensure the `imageBitmapFromUrl `function handles all possible edge cases, such as null or invalid URLs.
> 3. In general
>    
>    * You can use external methods to avoid code duplication. Which makes the code clearer and more readable
>    * You could add a few comments in the code at tricky moments to make rereading easier.
>    * I also read the pull review that Yshai did and I follow him on certain points (so I won't repeat them)
> 
> ### Overall
> * Overall, you did a very good job. The PR was necessary for the smooth running of the project

**Comment by ethanboren** [comment]
### Description:
* Added ImageBitmap to MarkerData in MapScreenTest.kt for better marker representation.
 * Introduced CountDownLatch to ensure the map is fully loaded before assertions.
 * Enhanced ProviderMapScreen and SeekerMapScreen to include images in markers.
 * Used LaunchedEffect to dynamically update markers based on data changes.
 
 ### Good things
 
 * The tests you did really help our project still work even in the future. It also makes it possible to maintain high line coverage. Thanks for that
 
 ### Things to Modify
 
 1. ProviderMap.kt:
    
    * The onClick functionality for markers is currently a TODO. Implement this or provide a comment explaining the expected behavior and future implementation plan.
 2. SeekerMap.kt:
    
    * Ensure the `imageBitmapFromUrl `function handles all possible edge cases, such as null or invalid URLs.
 3. In general
    
    * You can use external methods to avoid code duplication. Which makes the code clearer and more readable
    * You could add a few comments in the code at tricky moments to make rereading easier.
    * I also read the pull review that Yshai did and I follow him on certain points (so I won't repeat them)
 
 ### Overall
  * Overall, you did a very good job. The PR was necessary for the smooth running of the project

**Review by ethanboren — APPROVED** [review]
### Description:
- Added ImageBitmap to MarkerData in MapScreenTest.kt for better marker representation.
- Introduced CountDownLatch to ensure the map is fully loaded before assertions.
- Enhanced ProviderMapScreen and SeekerMapScreen to include images in markers.
- Used LaunchedEffect to dynamically update markers based on data changes.


### Good things
- The tests you did really help our project still work even in the future. It also makes it possible to maintain high line coverage. Thanks for that

### Things to Modify
1. ProviderMap.kt:
   - The onClick functionality for markers is currently a TODO. Implement this or provide a comment explaining the expected behavior and future implementation plan.

2. SeekerMap.kt:
   - Ensure the `imageBitmapFromUrl `function handles all possible edge cases, such as null or invalid URLs.
  
3. In general
   - You can use external methods to avoid code duplication. Which makes the code clearer and more readable
   - You could add a few comments in the code at tricky moments to make rereading easier.
   - I also read the pull review that Yshai did and I follow him on certain points (so I won't repeat them)
 
### Overall
- Overall, you did a very good job. The PR was necessary for the smooth running of the project

**Pull request merged**
