### PR TITLE
Harmonize text styles on registration pages according to typography conventions

### LINKED ISSUE #323: Text format harmonization
Text formatting and size should be adjusted for exemple in the 'You're all Set"
The figma screens containing relative info about size/police ect may be used for inspo

### LINKED ISSUE #413: Check the entire app to see that long text fields or fields that result from user input display the content correctly and do not break the UI
Use ellipsis or similar solutions for too long inputs, texts, numbers etc...

### PR DESCRIPTION
**Pull request by ethanboren**
### What does this PR do?
This Pull Request updates the text styles on all registration pages to ensure consistency and compliance with the project's typography conventions.

### Key Changes:
- Applied `MaterialTheme.typography` styles (`titleLarge`, `bodyLarge`, `labelSmall`, etc) to all text components on registration pages.
- Replaced hardcoded text sizes with centralized typography definitions.
- Improved readability and alignment with the design guidelines.

### Why is this needed?
- Ensures consistent text styles across the app.
- Aligns with the design system for a better user experience.
- Facilitates future updates to typography styles.

### How was this tested?
- Verified the visual appearance of all registration pages on multiple devices and screen sizes.
- Tested text scalability to ensure compatibility with accessibility settings (e.g., font size scaling).
- Ensured no regression issues in related UI components.
- Do not look at the design of the "not implemented yet" buttons because they will be deleted afterwards so it is normal if they are not beautiful
---

### Checklist:
- [x] Code follows the project's coding and design conventions.
- [x] Changes are documented where applicable.
- [x] All tests pass locally.
- [x] Screens were manually tested for responsiveness.

---

### Related Tickets/Issues:
- Fixes #323 
- Fixes #413

### CODE REVIEW

**Review by yshdb5 — CHANGES_REQUESTED** [review]
**Overall Comment:**  
This PR improves the codebase by cleaning up redundant UI elements, enhancing readability, and refining the user experience. The updates are thoughtful and contribute to cleaner, more maintainable code. Great work!

**Strong Elements:**  
1. **Consistency:** Using `Typography` consistently improves readability and maintainability.  
2. **UI Enhancements:** Updates like `Icons.AutoMirrored.Filled.ArrowBack` and refined `Typography` modernize the interface.  
3. **Modularity:** Replacing repetitive `TopAppBar` components with `TopAppBarInbox` shows great attention to reuse and modularity.  

**Areas for Improvement:**  
1. **Comments:** The refactoring of the typography throughout the app led to small bugs:

Some icons disappeared from the `ServicesScreen`:

Capture d’écran 2024-12-13 à 16 57 15

Also the ProviderItem cars seem to have been modified, they do not look the same as before (brush effect etc..):

Capture d’écran 2024-12-13 à 16 57 34

Little bug with the `SelectProviderScreen`:

Capture d’écran 2024-12-13 à 16 57 12

**Conclusion:**  
This PR is a strong step forward for the codebase and its maintainability. Please fix the little bugs and it will be perfect. Nicely done!

**Comment by yshdb5** [comment]
Thank you for the thoughtful modifications. All looks good to me.

**Review by yshdb5 — APPROVED** [review]

**Review by hjamaly — CHANGES_REQUESTED** [review]
### Overview

Great work on adding consistency to our app through a well harmonisation of text styles in different screens. The app is better than before and more professional . However, there is still 2 screens that needs improvement . For the 2 screens we don't need a gray background on the top bar and bio data in second screen is centered and don't have the same style as other titles. I make a complete simulation of an user flow and LGTM for all other screens  
Capture d’écran 2024-12-14 à 09 25 31
Capture d’écran 2024-12-14 à 09 30 57

**Review by hjamaly — APPROVED** [review]
LGTM ! Thank you !

**Pull request merged**
